alliance-genome/agr_loader

src/loaders/transactions/disease.py

had to re-merge the da node in order to get pub to recognize it.

fix evidence w/extra da node merge

---

src/mods/zfin.py

new ZFIN tarball reference. Individual file names according to spec

---

.gitignore
src/mods/fly.py
src/mods/human.py
src/mods/mouse.py
src/mods/rat.py
src/mods/worm.py
src/mods/zfin.py

Ran the loader locally (with full data). No errors and all tests passed.

Nov 27 Data Update

---

src/mods/zfin.py

just a file name change to comply with naming convention "feature" instead of "allele."

fixing zfin data file name

---

src/extractors/__init__.py
src/extractors/disease_feature_ext.py
src/extractors/disease_gene_ext.py
src/extractors/primary_data_object_type.py
src/mods/mod.py
src/mods/mouse.py
src/mods/worm.py

some refactoring, added enum, added data dump update

Allele disease

---

.gitmodules
README.md

adding agr_schemas as a submodule at 1.0.4 release tag.

adding release 1.0.4 as a submodule

---

src/extractors/obo_ext.py
src/mods/mouse.py
src/test/test_object.py

just a hard coding fix - making ontology link outs more generic is next on the list for xrefs.  
any chance we can get this reviewed real quick?

fix OMIM:PS hardcoding

---

src/loaders/transactions/go.py

@oblodgett  - maybe this will trigger another build of the test pipeline and be good to go?  Its not a fix for the error you're seeing on the test build, I can't reproduce that locally.  It looks like the XML library is reporting an issue - is gocd using the same requirements file that agr_loader itself is using (just brainstorming)?

small change for amigo href

---

.gitignore
src/aggregate_loader.py
src/extractors/__init__.py
src/extractors/geo_ext.py
src/extractors/imex_ext.py
src/extractors/mi_ext.py
src/fetch_index.py
src/files/__init__.py
src/files/zip_file.py
src/loaders/__init__.py
src/loaders/imex_loader.py
src/loaders/mi_loader.py
src/loaders/transactions/__init__.py
src/loaders/transactions/allele.py
src/loaders/transactions/disease_gene.py
src/loaders/transactions/geo_xref.py
src/loaders/transactions/imex.py
src/loaders/transactions/indicies.py
src/loaders/transactions/mi.py
src/test/schema_node_tests.py
src/test/test_object.py

First phase of interaction data. 
This pull request loads the Molecular Interaction ontology via EBI's Ontology Lookup Service (OLS) and also parses / loads the IMEX intact.zip data file. 
The IMEX module will be renamed and very slightly refactored to accommodate BioGRID + MOD interactions in the next phase.

Interactions phase 1 (AGR-790, AGR-791)

---

src/extractors/bgi_ext.py

no bug fixes, just a tiny bit of code clean up in prep for some more refactoring in 1.6.

code cleanup - reuse urlservice

---

src/extractors/bgi_ext.py
src/mods/worm.py
src/test/schema_node_tests.py
src/test/schema_rel_tests.py
src/test/specific_tests.py
src/test/test_object.py

pulling release-1.4.0 changes into develop.

Release 1.4.0

---

src/extractors/bgi_ext.py
src/test/specific_tests.py

Nobel Prize for Computer Science right here.

AGR-948 Remove special case for gene/spell xref page

---

.gitignore
requirements.txt
src/aggregate_loader.py
src/extractors/obo_ext.py
src/loaders/transactions/gene_description.py
src/loaders/transactions/go_annot.py
src/mods/fly.py
src/mods/human.py
src/mods/mod.py
src/mods/mouse.py
src/mods/rat.py
src/mods/sgd.py
src/mods/worm.py
src/mods/zfin.py
src/services/gene_descriptions/data_fetcher.py
src/services/gene_descriptions/descriptions_generator.py
src/services/gene_descriptions/descriptions_writer.py
src/services/gene_descriptions/genedesc_config.yml

initial integration - GO module only

Gene descriptions

---

src/services/gene_descriptions/descriptions_generator.py
src/services/gene_descriptions/genedesc_config.yml

set empty descriptions to "null" in neo4j instead of "No description available"

Genedesc nodesc hotfix

---

requirements.txt

- added specific tag for genedescriptions package in requirements.txt to freeze GD code before release
- removed '-e' option for GD package

fixed requirement version for genedescriptions package

---

src/aggregate_loader.py
src/test/schema_node_tests.py
src/test/schema_rel_tests.py

Lets see how long this takes on build.alliancegenome.org.  
enables phenotype loader.

enable phenotype loader and tests

---

requirements.txt
src/aggregate_loader.py
src/extractors/so_ext.py
src/mods/fly.py
src/mods/human.py
src/mods/mod.py
src/mods/mouse.py
src/mods/rat.py
src/mods/sgd.py
src/mods/worm.py
src/mods/zfin.py

Release 1.6.0 s3 file updates

---

requirements.txt
src/mods/mod.py

fixed bugs with 1.6 files
- encoding error with ZFIN GO annotations file - fixed in loader
- upper case qualifiers in MGI GO annotations file - fixed in gene description package and added new tag in pip requirements file

Release 1.6.0 gdfix

---

src/extractors/obo_ext.py
src/test/specific_tests.py

adds more parsing to isa relation (will get better with new obo extractor)
adds test to check for DO terms with missing is_a relations.

Patch do isa

---

.travis.yml
requirements.txt
src/aggregate_loader.py
src/extractors/obo_ext.py
src/loaders/do_loader.py
src/loaders/go_loader.py
src/loaders/transactions/do.py
src/loaders/transactions/gene_description.py
src/loaders/transactions/go.py
src/services/gene_descriptions/data_fetcher.py
src/services/gene_descriptions/descriptions_generator.py
src/services/gene_descriptions/descriptions_writer.py
src/services/gene_descriptions/genedesc_config.yml

- replaced custom obo parsers with ontobio (Dustin)
- new gene descriptions code based on ontobio
- added gene description disease module

Genedescriptions disease agr 1004

---

src/extractors/phenotype_ext.py
src/test/test_object.py

changed the phenotype loader for 1.0.0.4 already; this handles pheno data with no pub med id

handle no pub med id

---

src/aggregate_loader.py
src/extractors/obo_ext.py

Adjusting to pull ontology node description from ontobio node correctly.

Agr 1032 definitions fix

---

src/extractors/phenotype_ext.py
src/files/json_file.py
src/mods/sgd.py
src/mods/zfin.py
src/test/specific_tests.py
src/test/test_object.py

SGD has new file
ZFIN bug fixes

Update zfin + sgd file 1.7

---

src/aggregate_loader.py
src/extractors/phenotype_ext.py
src/files/json_file.py
src/mods/human.py
src/mods/mouse.py
src/mods/rat.py

update data files for MGI, RGD, Human

Update data files

---

src/aggregate_loader.py
src/extractors/phenotype_ext.py
src/files/json_file.py
src/mods/human.py
src/mods/mouse.py
src/mods/rat.py

this is a merge back into develop from the 1.7 data files patch that went in this morning.

Update data files merge

---

src/extractors/obo_ext.py

Hopefully doing this correctly. Simple correction to de-clutter the logs.

Removing print subset debug line

---

src/extractors/obo_ext.py
src/test/schema_node_tests.py

Pulling in definition URLs through ontobio correctly.

Parsing defLinks correctly - AGR-1134

---

src/aggregate_loader.py
src/extractors/bgi_ext.py
src/extractors/disease_allele_ext.py
src/extractors/disease_ext.py
src/extractors/disease_gene_ext.py
src/extractors/geo_ext.py
src/extractors/mi_ext.py
src/extractors/mol_int_ext.py
src/extractors/obo_ext.py
src/extractors/obo_ext_old.py
src/extractors/ontology_extractor.py
src/extractors/phenotype_ext.py
src/extractors/resource_descriptor_ext.py
src/extractors/wt_expression_ext.py
src/files/csv_file.py
src/files/download.py
src/files/json_file.py
src/files/s3_file.py
src/files/tar_file.py
src/files/txt_file.py
src/files/xml_file.py
src/files/zip_file.py
src/loaders/transactions/bgi.py
src/loaders/transactions/transaction.py
src/services/resource_descriptor.py
src/test/test_object.py

I am by no means a python-dev, but we need to do something.

Added logging to output so we can see timings

---

src/extractors/mi_ext.py
src/extractors/mol_int_ext.py
src/loaders/transactions/mi.py
src/services/resource_descriptor.py

Includes cross references to all identifier databases.

AGR-791 Second pass on interactions loading

---

src/extractors/mol_int_ext.py

Additional pass on resolving identifiers for interaction loading.

AGR 791 improvements

---

src/fetch_index.py
src/mods/rat.py
src/mods/worm.py

Just an update to WB and RGD/human files. 
Commented out gene->disease via orthology to get the pipeline going again.

update WB file

---

src/loaders/transactions/gene_disease_ortho.py

I am commenting out, instead of removing it, so that if/when they change their minds we still have the other half of the query.

commenting out disease via orthology via allele

---

src/mods/fly.py

updated FlyBase data: non-coding genes, more uniprot xrefs, schema 1.0.0.7

---

src/extractors/obo_ext.py
src/mods/worm.py

Data freeze 2.0

---

.travis.yml
src/extractors/mi_ext.py
src/extractors/mol_int_ext.py
src/loaders/transactions/mi.py

This PR fixes a data filtering bug which was preventing some of the interactions from properly loading. It also adds definitions to MITerms as they're loaded into Neo.

Interactions improvements AGR-791

---

src/loaders/transactions/gene_disease_ortho.py

This change was requested by @sibyl229 an @cmpich and is for making the orthologous gene the inferred disease to gene association was generated from.

Adding link to FROM_ORTHOLOGOUS_GENE to diseases inferred through orthology

---

requirements.txt
src/aggregate_loader.py
src/services/gene_descriptions/data_extraction_functions.py
src/services/gene_descriptions/descriptions_generator.py
src/services/gene_descriptions/descriptions_writer.py
src/services/gene_descriptions/genedesc_config.yml

This PR adds orthology sentences to the descriptions and generates report files in json format that are automatically uploaded to the S3 bucket (only for the release pipeline).

Gene descriptions reports and orthology module

---

src/mods/zfin.py

an update to ZFIN data files after local anatomical ontology update.

update zfin data file

---

src/aggregate_loader.py
src/loaders/transactions/wt_expression.py
src/test/specific_tests.py

Just a tweak to the GOCC other expression query to return other only when no other gocc records.

Fix gocc other relation

---

src/extractors/mol_int_ext.py

This fixes the bug associated with interactions having multiple identifier resolutions not linking out properly via xrefs.

AGR-1155 xref bug fix

---

.travis.yml
src/aggregate_loader.py
src/extractors/ortho_ext.py
src/test/specific_tests.py

checking to see if modified .travis.yaml and dynamic ortho test data will work via travis.

Add back deg tests

---

src/mods/fly.py
src/mods/human.py
src/mods/mouse.py
src/mods/rat.py
src/mods/sgd.py
src/mods/worm.py
src/mods/zfin.py

migrate new gaf files back into develop

AGR-1310 (develop)

---

src/aggregate_loader.py
src/common.py
src/data_manager/data_file_manager.py

- added Singleton class and transformed DataFileManager into a Singleton
- moved self.process_config() method of DataFileManager inside the __init__ method
- added ContextInfo singleton to share common variables

Agr 1234 reload the loader dm singleton

---

src/etl/bgi_etl.py
src/etl/do_etl.py
src/test/schema_node_tests.py
src/test/specific_tests.py

add apoc function apoc.number.parseInt to genomic location start/end values on insert into neo4j.

add apoc to int to genome location AGR-1401

---

src/aggregate_loader.py
src/config/default.yml
src/config/develop.yml
src/config/local_submission.json
src/config/test.yml
src/config/travis.yml
src/config/validation.yml
src/data_manager/data_file_manager.py
src/etl/bgi_etl.py
src/etl/do_etl.py
src/etl/helpers/etl_helper.py

fix self closure relation
add sort order for species
add ortho to submission system and retrieve from submission system

fix self closure AGR-1418 AGR-1424 AGR-1425

---

src/config/local_submission.json

Tested this locally with a full build as well.

Updated interactions file for 2.1 release.

---

src/etl/molecular_interaction_etl.py

`page = 'gene/MODinteractions'`

Small bug fix for interaction mod xrefs. AGR-1136

---

src/etl/gene_descriptions_etl.py

PR to merge hotfix for AGR-1476 into 2.1 release branch

AGR-1476 hotfix

---

requirements.txt
src/aggregate_loader.py
src/config/default.yml
src/config/develop.yml
src/config/local_submission.json
src/config/test.yml
src/config/travis.yml
src/config/validation.yml
src/data_manager/data_file_manager.py
src/etl/__init__.py
src/etl/allele_etl.py
src/etl/variation_etl.py
src/files/json_file.py
src/test/schema_node_tests.py
src/test/schema_rel_tests.py
src/test/specific_tests.py
src/test/test_object.py

Variant loader added via the local submission system (to be moved to the new file management system when it is available).
Added tests for 3 bits of ZFIN data; need test data from other MODs (will be added in subsequent PR).

Variant loader AGR-1417 

---

docker-compose.yml
src/config/default.yml
src/config/develop.yml
src/config/local_submission.json
src/config/test.yml
src/config/travis.yml
src/data_manager/data_file_manager.py
src/etl/helpers/neo4j_helper.py
src/etl/variation_etl.py
src/test/specific_tests.py
src/test/test_object.py

Sheepishly add more test data, fix whole-data set errors (vs. passes in test data set), slipped in FB files and removed verbose logging.

Variant loader

---

src/aggregate_loader.py
src/common.py
src/data_manager/data_file_manager.py
src/default_env_vars.yml
src/etl/etl.py
src/etl/gene_descriptions_etl.py
src/etl/helpers/neo4j_helper.py
src/files/s3_file.py
src/transactors/neo4j_transactor.py

- context info singleton now reads env vars default valued from file
- if default value is 'none' and the variable is not set in the environment the context info raises an exception
- vars containing boolean strings 'true', 'True', 'false', and 'False' are automatically converted to bool

read default env vars from file and set them in context info singleton

---

src/config/local_submission.json

This is a newly built file that fixes a minor bug in the last interactions update. I thought the interactions were updated ~2 weeks ago but it was either reverted or not updated.

Fixed update file for 2.2

---

src/data_manager/data_type_config.py
src/files/download.py
src/files/s3_file.py
src/files/tar_file.py
src/files/zip_file.py
src/transactors/csv_transactor.py

As discussed with the pull request for Ferret. I think I have found all the spots this is in the code!

changing everywhere I can find the way file paths are joined

---

src/etl/ECOMAP_etl.py

file format changed with AGR-1623, fixing parser.

fix ecomap loader

---

src/config/local_submission.json
src/config/test.yml
src/etl/mi_etl.py

Tried to get this in the pre-processing pipeline but it more appropriately fits here.

AGR-1281 new

---

docker-compose.yml
src/config/develop.yml
src/default_env_vars.yml
src/etl/vep_etl.py
src/test/specific_tests.py
src/test/test_object.py

- post-process RGD:id to match gene node.

fix RGD variant consequences

---

src/config/default.yml
src/config/develop.yml
src/config/local_submission.json
src/config/test.yml
src/config/validation.yml
src/etl/helpers/etl_helper.py

Removed orthology from local_submission JSON and fixed human name spelling in config YAML files.

AGR-1879 patch

---

requirements.txt
src/etl/gene_descriptions_etl.py

- Updated requirements to use latest agr_file_generator version in order to use new header template
- Added taxonIDs to gene description headers

AGR-2037 - gene description download file headers

---

src/etl/allele_etl.py
src/etl/htp_metadatasample_etl.py
src/etl/htp_metadataset_etl.py
src/etl/variation_etl.py
src/test/specific_tests.py
src/test/test_object.py

- keep note unique by note text instead of creating an id to help reduce duplicates
- added more test data.

Bug fixes3.2.0

---

src/etl/htp_metadatasample_etl.py

add uuid to datasetsample instead of compound key AGR-2480

---

.env
Dockerfile
Makefile
docker-compose.yml

Please review and approve (once fit), but do not merge yet (I will do so after approval, once I updated the necessary GoCD pipelines, one pipeline at a time).

AGR-2590 loader

---

src/aggregate_loader.py
src/data_manager/data_file_manager.py
src/files/download.py

Retrying 10 times in less than a second is likely to fail 10 times upon temporary network or similar issues. When still failing after retrying over some time, code should stop rather than continue silently in order to catch errors like S3 temporarily failing.

Fixed file download to sleep between retries and fail and abort after x retries

---

src/etl/disease_etl.py

Small experimental condition neo4j model modification on request of @cmpich: relation type will now be stored as edge label rather than edge property.

AGR-2541 Moved experimental condition relation type to edge label

---

src/etl/disease_etl.py
src/etl/helpers/experimental_condition_helper.py
src/test/specific_tests.py

Made a small update to include the condition statement into the ec unique key (as the conditionstatement sometimes contains key information not found in any other fields, which defines the experimental condition).

Experimental Condition uniqueness definition update (AGR-2925, AGR-2541)

---

src/etl/vep_transcript_etl.py

Switch %3D for = in HGVSp names

HGVSp unicode fix

---

src/test/specific_tests.py

Key changed due to changes made to ZFIN DAF in SCRUM-1195

Update primary key for ZFIN experimental condition

---

requirements.txt
src/etl/gene_descriptions_etl.py

Removed dependency on agr_file_generator and hardcoded file header templates in the gene descriptions etl. Added requirements to fix broken dependency needed by ontobio 1.20.0

Gene desc header hotfix
