alliance-genome/agr_loader

src/loaders/transactions/bgi.py
src/loaders/transactions/indicies.py
src/loaders/transactions/orthology.py

1. indexes on the UUID fields? - Already exist (as Association {primaryKey})
2. Why are all CrossRefences labeled as Entity’s? - Removed :Entity
3. Remove Indexes: Location(primaryKey), LocationObject - Done
4. CrossReferences -> Genes’s are Broke - Fixed
5. Can the Association nodes for Orthology be Labeled with something? - Following Sierra's naming convention and used `:OrthologyGeneJoin`.

Aug 31 patch

---

src/aggregate_loader.py
src/services/gene_descriptions/data_extraction_functions.py
src/services/gene_descriptions/descriptions_generator.py
src/services/gene_descriptions/genedesc_config.yml

hotfix to include key diseases in the descriptions by increasing the number of displayed terms from 3 to 5 and other small changes

Genedescriptions reports and orthology

---

src/aggregate_loader.py
src/loaders/transactions/gene_disease_ortho.py

I have tested this by fully building the database from scratch and then testing different orthologous genes. Mainly focusing on gene MGI:98371 and HGNC:11204
I don't think this change fixes anything but it makes the query a lot more readable. 
@sierra-moxon if you could look at the results and see if you can confirm the data in the database seams correct. By confirm I mean look at the edges associated with the two genes above and see if you think they look right
@cmpich Do you think you could look into the query from the API / indexer. The curators are saying that nothing is showing up for MGI with regards to gene-disease associations. I will forward you the email with more information. 
* Staring at these nodes and edges for these associations gets to be quite complicated. I did the best …

I was using neo4j version 2 Cypher query syntax - looks clean now

---

src/etl/disease_etl.py
src/etl/helpers/disease_helper.py
src/test/schema_node_tests.py
src/test/specific_tests.py

Hi Sierra, 
I ran this locally and it adds the dateAssigned from the JSON file being submitted. I have created one test to make sure it is there. In the future, we can write more tests.. not sure what they will be. JSON Schema validation already has the field as required so it should always exist. I am about to use this field for generating the DAF so I might run into issue which I will write tests for :).

added property to disease entity join and tests for dateAssigned

---

src/etl/bgi_etl.py
src/etl/helpers/assembly_sequence_helper.py
src/etl/variation_etl.py

I have made the decision to never have the chr prefix on chromosome names. This would be nice to keep consistent throughout the Alliance project. I have not run this with the full dataset.

Removing chr from chromosomes variation etl

---

docker-compose.yml
src/etl/variation_etl.py
src/test/schema_node_tests.py
src/test/test_object.py

- migrate unique key on Variant node from uuid to HGVS nomenclature in preparation for return data from VEP
- add tests for Variant
- remove dependency on NEO4J_dbms_import_csv_buffer__size parameter (no longer needed after tracking down the single variant anomaly).

Variant key

---

src/etl/bgi_etl.py

The issues is that the strand was not making its way through with the genomeLocation information. It looked clear to me that the code just needed a small adjustment

fixing the missing strand AGR-682

---

docker-compose.yml
gene_descriptions.yml
src/default_env_vars.yml

- new BGI file for MGI
- AGR-1729 bug fixed (expression term missing from blacklist)
- changed docker-compose.yml and default_env_vars.yml to point to FMSprod instead of FMSdev as default option for the loader

Gene descriptions - new files for MGI and expression blacklist fix

---

gene_descriptions.yml

graylist terms should be in the blacklist to avoid picking them as common ancestors while trimming

fix: graylist terms added to blacklist

---

src/aggregate_loader.py
src/config/default.yml
src/config/develop.yml
src/config/local_submission.json
src/config/test.yml
src/config/validation.yml
src/etl/gene_descriptions_etl.py
src/etl/molecular_interaction_etl.py

Temporarily hardcoding the extracted interactions filename.
The current data_config approach doesn't allow us to update the filepath once the compressed file is uncompressed. There will need to be a minor rewrite of handling .tar.gz files in the near future in order to remove the hardcoded filename from the molecular interactions ETL. I'll be making a JIRA ticket for 3.1.

Updates for 3.0.0 interactions.

---

requirements.txt

Changed version of gene description software - Added patch to fix wrong SGD GAF file on the fly
Change in the GD code: 
- Add missing underscore to qualifiers in GAF files.
- SGD is working to fix the bug at the source but this patch avoids to add further delay to 3.0 release

patched version of GD software to fix SGD GAF file on the fly

---

src/etl/gene_descriptions_etl.py
src/etl/generic_ontology_etl.py

some GCI (general concept inclusion) axioms are wrongly interpreted as conventional relations and this is causing loops on FBBT root terms. This PR adds a filter to avoid loading them from the Alliance custom obo loader and removes the code previously added to the gene description etl to manage the loops.

fix(generic_ontology): filter out gci axioms

---

src/etl/bgi_etl.py
src/etl/gene_descriptions_etl.py
src/test/specific_tests.py

This PR reverts the gene dataProvider field in neo for human genes from "HUMAN" back to "RGD". This restores human gene descriptions. Just to be extra safe, the GD ETL now retrieves human genes from neo without using the dataProvider field, and there are additional unit tests.

Revert human

---

src/etl/helpers/neo4j_helper.py

I think this is a query conflict/timing issue rather than a code issue.  Commenting out this key for now so that build can progress with all the other fixdes, and I will fix the timing issue in a subsequent PR.  (aka: the full load passed all tests for me locally before I merged in the changes that just failed on this category tag test on build).

remove category tag unique key

---

README.md
src/etl/do_etl.py
src/etl/ecomap_etl.py
src/etl/generic_ontology_etl.py
src/etl/go_etl.py
src/etl/helpers/obo_helper.py
src/etl/mi_etl.py
src/etl/so_etl.py

This pull request adds code to pull the metadata out of the header and place it into Nodes with the label OntologyFileMetadata for each ontology file. The design is such that it transforms fields such as "release-version" to camelcase as that is what we use in our database and that Neo4J doesn't allow "-"s in the field names. Althought this is pulling all the fields through they don't all have to be used. As more fields are standardized between the Ontology files the more fields we will be able to take advantage of. That being said the code won't have to change if we want to use more fields as they are being pulled in if they are in the header.
I have tested this by running it locally and querying the Neo4J interface. To me it looks correct.

Currently tested by querying the database query interface AGR-2294

---

src/etl/gene_descriptions_etl.py

- curators no longer need to open json files directly thanks to the report tool
- some prettified json files are too large and make the report tool crash when decompressing them

feat(gene_descriptions): do not prettify json files

---

requirements.txt

GO rule 26 was removing IBA annotations from the GAF files used to generate gene descriptions. This PR points to a patched version of ontobio that excludes that specific rule.

fix(ontobio): using a patched version of ontobio to exclude GO rule 26

---

src/test/specific_tests.py

There are a number of variations submitted by ZFIN where the
specified reference allele sequence doesn't match the reference
genome sequence at the specified positions.  ZFIN have requested
that these be removed.  However, one of those variations is used in
the current HGVSg deletion test so the test need to be updated to
use a different variation.

Change variant used for HGVSg deletion test - AGR-3024

---

gene_descriptions.yml
requirements.txt
src/etl/gene_descriptions_etl.py
src/test/test_object.py

This PR adds a new sentence template for 'is_active_in' qualifiers, and points to a new agr_genedescriptions release that includes the code to add the related sentences to the descriptions. The new agr_genedescriptions version also fixes a bug that was previously managed by patching ontobio, and the loader can now use a standard version of ontobio instead of the patched one.

Added missing 'is active in' template for GOCC sentences

---

gene_descriptions.yml

Fixed templates for gene descriptions: added predictions for GO BP and removed extra verb

AGR-3067: fixed bugs in gaf 2.2 gene description templates

---

src/etl/transcript_etl.py

The SOTerm name for SO:0001877 has changed from 'lnc_RNA' to
'lncRNA'.  This was preventing GFF entries with feature type set
as 'lnc_RNA' from loading.  The transcript_types and possible_types
arrays have been updated to 'lncRNA', and the feature_type_name
variable is set to 'lncRNA' if the old form is found.  This allows
transcripts to be loaded with either form of the name.

Changes due to SO:0001877 name change

---

src/test/specific_tests.py

The entries in the possible_feature list in the transcript loader
need to match the names of the loaded SO objects, otherwise those
features do not get loaded.

Add test for SOTerm names used in transcript loader

---

src/etl/helpers/experimental_condition_helper.py
src/test/schema_node_tests.py

Added the storage of the `conditionId` property as a `:ExperimentalCondition` node property. This was incorrectly missed in the initial implementation, while it was (correctly) used as part of the (concatenated) `primaryKey`.
While this is not the cause of SCRUM-1001, it is related to the same `conditionId` property.

SCRUM-1001: Added experimental condition conditionId property storage

---

requirements.txt

The current loaderBuild and loaderPR pipelines are failing on `genedescriptions.ontology_tools`. As there is a new version of the genedescriptions tool available (as of last Friday), I hope using this new version will solve the currently observed errors.

Bumped genedescriptions from 3.2.4 to 3.2.5

---

src/etl/transcript_etl.py

Make sure curie (which becomes primaryKey) is unique and ensure CDS linked to correct Transcript by searching for both gff3ID and dataProvider fields.

Avoid issues with duplicate transcript names across MODs

---

src/etl/genetic_interaction_etl.py
src/etl/molecular_interaction_etl.py
src/test/specific_tests.py
src/test/test_object.py

@christabone @oblodgett - I've not been able to replicate the duplicate Association node primaryKey error on my local system, although I was only loading XB and RGD data.  
The only places that I've found an Association node primaryKey to be created without being in a MERGE query is in the interaction ETLs, so I've switched those CREATE queries out for MERGE ones here.  
They should have been unique even if there was duplicate data as the primaryKey is just a randomly generated UUID, but perhaps we are seeing the same issue as with the duplicate GenomicLocations?  Worth a shot?

Loader test fixes (maybe)

---

src/etl/gene_disease_ortho_etl.py

- directed relationships were used (possibly?) to speed up the disease via ortho query
- using undirected [ORTHOLOGOUS] relationships between genes returns exactly the same results for "old" MODs and adds unidirectional data from XBXL and XBXT orthology that was missing when using directed relationships

fix(disease_via_ortho): using undirected relationship to read ortho data for disease via ortho

---

src/etl/gene_descriptions_etl.py

The gene descriptions etl was using helper functions to retrieve species names and taxon ids to include these fields in the download file headers. These functions were removed from the helper because they were causing issues with XB double species. and the gene desc file headers contained a default species name and taxon id.
This PR adds static maps from provider to species and taxon id in the gene descriptions etl and uses the maps to place the correct values in the headers.

Fix species name and taxon id in descriptions download files header (tsv and txt)
